### PR TITLE
Firebase Authentication

### LINKED ISSUE #55: Firebase Authentication
Authenticate users/admins during login

### LINKED ISSUE #67: Add Protection for API Routes
Only authenticated users should be able to access all API routes and each user should only have access to the routes necessary for their role.

### PR DESCRIPTION
**Pull request by petabite**
### Administrative Info
[GitHub Issue #55 and #67]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
- connect login/signup pages to firebase
- add auth routes
- add and use route protection middleware

### Testing
- created test user and ensured routes were blocked properly and the correct role shows up in the header

### Confirmation of Change 
- make sure `.env` files are updated with firebase credentials 
- run both backend and client
- head to `/login` page
- test user:
    - email: test@test.test
    - password: testing

### CODE REVIEW

**Review by dnanjunda — CHANGES_REQUESTED** [review]
This looks great Philip! It's a huge PR so great job on that. Couple things I noticed:

1. There's a lot of warnings so make sure to fix all of them. Most of them are due to console statements.
2. It looks like you are navigating to the dashboard page when a user logs in. For admins, it should go to the "Pending Applications" page because they don't have the dashboard page. I'm not sure if you're planning to change the code later to implement this but it might be easier to do it now?
3. If possible, add a little bit of space above and below the error message on the log in page.
Screen Shot 2022-05-24 at 8 43 51 PM

4. Make the minimum password length 8 since that's more commonly used.

**Review by willji0023 — COMMENTED** [review]
This is epic!

Small thing I noticed that seems to only happen on tablet view is with the addition of the welcome message in the header, the text overflows out of the header.
image

**Review by parth4apple — APPROVED** [review]
LGTM

**Review by willji0023 — APPROVED** [review]
LGTM, approved

**Review by dnanjunda — APPROVED** [review]
LGTM! Great job Philip!

**Pull request merged**
