### PR TITLE
Feature/artyom2001/landing login

### LINKED ISSUE #5: Landing and login pages

### PR DESCRIPTION
**Pull request by artyom2001**
### Administrative Info
[GitHub Issue #5]

### Changes
What changes did you make?
- Created custom components for the header, form (for landing/login/register), and buttons.
- Created and styled landing and login pages, with functional inputs and buttons (except Login button)
- Made pages responsive and suitable for mobile users.

### Testing
How did you confirm your changes worked? 
- Compared my page designs to the Figma design
- Tested the landing and login pages for various screen sizes
- Confirmed buttons are functional

### Confirmation of Change 
- Go to the landing page at "/" or the login page at "/login"

landing_desktop
login_desktop

### CODE REVIEW

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Looks nice Artyom! There's no major issues so these are all quick fixes:

1. Can you style the buttons (mainly Foster and Admin) to match the designs? They look good on mobile/tablet but on desktop they're too rounded.

Figma:
buttons_design

Your code:
buttons_code

2. Similar to the comment above, make the input boxes (email and password) like the designs as well. This is again mainly on desktop, as they look too rounded and small.

Figma:
input_design

Your code:
input_code

3. Regardless of if I click Foster or Admin on the landing page, it says "foster log in" on the login page. Just change this to "admin log in" when Admin is clicked.
4. On some of the mobile screens, the white box that contains the input fields and login button overflows into the header. I think this is because the height of this white box is constant and not responsive.
login_mobile

5. Can you add css for the iPad range (750 to 1050 px) to make the login component wider. It looks too cramped right now.
login_ipad

6. This is a nitpick but can you shift the dog image up a bit so that there's some space between that and the black text in the bottom right corner (on desktop)?

**Review by petabite — COMMENTED** [review]
This is looking really great! Dhanush covered pretty much all the visual things I could find as well. I can approve this after those changes are implemented.

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Almost there! Couple minor things I noticed:

1. Can you vertically center the white component on mobile? It looks a bit weird right now:
login_mobile

2. Add a bit more space between the input fields, login button, and sign up button. If you look at your tablet/ipad design, that looks much better. Try to make desktop the same as well. This is how it looks for me right now:
login_desktop

3. For the "foster" and "admin" buttons, I think you can add more padding around them. Again, the tablet/ipad ones look perfect so refer to those.
4. Let's just go with the mobile design on ipad/tablet screens. The dog image just looks squished and it's not worth keeping.
5. Like we discussed at the meeting, add a prop to pass which button is clicked and have the appropriate title (foster or admin log in).

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Few really small things Artyom:

1. I think you removed the "email" and "password" placeholders for the input fields on mobile and ipad. Can you add them back?
2. Since you've implemented the sign up pages on mobile as well, can you add the sign up button for mobile and ipad? Put it in the same location as it is on desktop.
3. Add a bit more padding between the log in button and the sign up button on desktop.
4. I think you missed number 5 from my previous comment. Can you address that?

**Review by petabite — APPROVED** [review]
LGTM

**Review by dnanjunda — APPROVED** [review]
LGTM!

**Pull request merged**
