### PR TITLE
Fosters Page

### LINKED ISSUE #19: Fosters pages

### PR DESCRIPTION
**Pull request by petabite**
### Administrative Info
[GitHub Issue #19]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
- add Fosters pages for admin view (`/fosters`)

### Testing
- manually changed the `role` variable to make sure each view displayed correctly

### Confirmation of Change 

image

### CODE REVIEW

**Review by portoaj — COMMENTED** [review]
I have some minor feedback - mostly visual since most of the components don't have a backend component to test with at the moment.
1. The corners of the table should be rounded according to the Figma:
image
2.The top row of the table with the labels shouldn't have the column lines.
image
3.The items of the navbar should match what the figma navbar has. Might need to reach out to  Parth to make sure this part of the navbar is modular
image

I think we could probably push this PR through without the first 2 points but we might as well just fix them now. The last point about the navbar is definitely something we need to address though.

**Comment by portoaj** [comment]
Everything looks good so once you fix the merge conflict pm me on Slack and I'll approve the PR.

**Review by portoaj — APPROVED** [review]
Good job Philip 👍

**Review by dnanjunda — APPROVED** [review]
Looks great Philip!

**Pull request merged**
