### PR TITLE
Feature/portoaj/created dashboard components

### LINKED ISSUE #3: Dashboard page

### PR DESCRIPTION
**Pull request by portoaj**
### Changes
What changes did you make?
- Added DashboardCard, DefaultBody, Header, and IconButton components
- Created Dashboard Page using the above components

### Testing
- Compared Dashboard page against Figma schematic

### Confirmation of Change 
Can navigate to dashboard page at the /dashboard route

Dashboard Page
dashboardexample

### CODE REVIEW

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Great job Andrew! This is pretty close to done. Just a few sizing issues to fix:

1. In general, everything looks a little too big. Looking at the code, you're mainly using px. I would suggest using vw or vh instead. You can use an online converter to convert between the two.
dashboard

2. Same thing as above for mobile. The card looks a little too big and there's some position issues for certain widths. Just check all the devices in inspect element to test your mobile views.
dashboard_mobile

3. This is a nitpick, but can you add a little bit of space between the Sign Out button and the top of the screen? You can also move it all the way to the right.
4. You have all your css files in the "styles" folder right now. Just move those to the css folder.

**Review by dnanjunda — CHANGES_REQUESTED** [review]
This is better Andrew! There are still a few issues though:
1. The "sign out" button is still in the same position. Can you move it further to the right and add a bit of space between the button and the top of the screen?
2. It looks like the dashboard card component isn't resizing. So, on some mobile screens it takes up the whole width:
dashboard_mobile
The welcome text also seems to be too big here. I think the TAP image might be too big so double check those sizes.


3. For the dashboard card, can you shift the image and text down a bit to look like this:
dashboard_card

4. I'm not sure what it is, but everything still looks too big to me. Try making the TAP logo smaller like in the designs and see if that helps.
Figma:
Dashboard_ design

Your code:
dashboard

5. Merge main and include the navbar since that's ready to go.

**Comment by artyom2001** [comment]
Hey Andrew, 
I spent some time testing out your branch and I had similar issues that Dhanush was describing. 
Mainly, a lot of the sizing looks a little too big on my screen, even when using responsive dimensions using dev tools.

Besides the bugs that Dhanush mentioned, I want to add some of my observations:

image

The dimensions here are set to 1783x1080, which is what is used on the desktop designs on FIgma.
I think the positioning of everything looks very close, but the font sizes are still too big, since the header TAP line overflows to a second line. I think making the logo smaller, shifting the "Welcome" text to the left, and shifting the "Sign Out" button to the right will fix this issue. 

This could also be caused by the wrong default font, which I will bring up in today's meeting, since I had issues with font sizing due to this as well.

Otherwise, good job on the dashboard page! Once these bugs are fixed, I will use your header component in my own branches as well so things look cleaner.

**Review by artyom2001 — COMMENTED** [review]
Hey Andrew, 
I spent some time testing out your branch and I had similar issues that Dhanush was describing. 
Mainly, a lot of the sizing looks a little too big on my screen, even when using responsive dimensions using dev tools.

Besides the bugs that Dhanush mentioned, I want to add some of my observations:

image

The dimensions here are set to 1783x1080, which is what is used on the desktop designs on FIgma.
I think the positioning of everything looks very close, but the font sizes are still too big, since the header TAP line overflows to a second line. I think making the logo smaller, shifting the "Welcome" text to the left, and shifting the "Sign Out" button to the right will fix this issue. 

This could also be caused by the wrong default font, which I will bring up in today's meeting, since I had issues with font sizing due to this as well.

Otherwise, good job on the dashboard page! Once these bugs are fixed, I will use your header component in my own branches as well so things look cleaner.

**Review by artyom2001 — APPROVED** [review]
Everything seems to work as expected and the design is very responsive for every screen resolution I tested. Fixed all issues from the previous review. 
Also, the header component is very convenient for other parts of the website. May need to add a few variables to add some custom HTML as well.
Otherwise, everything looks good and can be merged with the main branch.

**Review by dnanjunda — APPROVED** [review]
LGTM! Great job persevering and getting it done.

**Pull request merged**
