### PR TITLE
Feature/artyom2001/sign-up-pages

### LINKED ISSUE #31: Signup and Auth Pages

### PR DESCRIPTION
**Pull request by artyom2001**
### Administrative Info
[GitHub Issue #31]

### Changes
What changes did you make?
- Created a custom component for the Register page using my IntroForm and Button components
- Created and styled the signup page and linked it to the "Sign Up" button on the login page.
- Created a temporary solution for mobile authentication (will make it more workable with libraries)
- Added all requested styling changes from the login page to the signup page.
- Made pages responsive and suitable for mobile users

### Testing
How did you confirm your changes worked? 
- Compared my page designs to the Figma design
- Tested the signup pages for various screen sizes, including the smallest iPhone sizes

### Confirmation of Change 
- Go to the signup page at "/register" or press "Sign Up" on the login page
- To see the temporary mobile authentication page, comment out the IntroForm component in Register.js and uncomment the other Form comment. You should see it on the page at "/register". 

| Register Page |
image
| Drop Down Menu |
image
| Mobile Authentication Page (subject to change) |
image

### CODE REVIEW

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Looking nice! Before you work on the changes, please merge main with your branch and fix the merge conflicts as there's a lot of them. Let me know if you need help with any of them.

1. The sign up page looks the same for both "Foster" and "Admin." Can you add the sign up page for "Foster" specifically, which shouldn't have the dropdown for selecting a role?
2. Change the title to "Admin Sign Up" instead of "Management Sign Up." It's just more appropriate in this case. Also, the first dropdown option should be "Management" instead of "Manager."
3. When an input field is selected, it has the blue border around it. Can you get rid of that?
4. The button for the sign up page should say "Continue" instead of "Sign Up."
5. The white form component overlaps a bit on smaller screen heights. Try getting rid of some of the white space at the bottom of this form (below the log in button). You can also try resizing the component by height since it doesn't do that right now.
Screen Shot 2022-05-18 at 11 50 54 PM

6. The placeholder text isn't quite centered within the input boxes. This is mainly for mobile but also a little bit for desktop. Also, can you specify the font size of the placeholder text using vw or vh, only for desktop? It looks super big within the input box (see image above).
Screen Shot 2022-05-18 at 11 53 54 PM

7. For most of the screen sizes, the text overlaps on the authentication page. It looks like the "please enter the..." text doesn't resize at all. Can you fix this?
Screen Shot 2022-05-18 at 11 56 49 PM
Screen Shot 2022-05-18 at 11 57 02 PM

8. For the sign up key, you currently have to click in each box to type the digit. Can you have it automatically switch to the next one once the user enters a digit?

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Much better Artyom! Couple things I noticed:

1. I know I asked you to make the placeholder text size smaller on desktop but it looks too small now, especially for the login form. You might need to specify it separately for login and sign up, because the input fields are bigger on the login page.

Screen Shot 2022-05-23 at 8 39 32 PM

Screen Shot 2022-05-23 at 8 39 51 PM

2. There's still a blue border for the "Re-enter Password" field. Can you remove it there as well?
3. On mobile and iPad screens, the "I am a..." text is behind the dropdown. This was fine before so it's probably because of your recent commit.

Screen Shot 2022-05-23 at 8 36 21 PM

Screen Shot 2022-05-23 at 8 36 11 PM


4. Please take a look at number 1 from my previous comment. You might have missed it.

**Review by petabite — CHANGES_REQUESTED** [review]
Looking good! I think you may have accidentally merged an older version of main into your branch which deleted some files (the ones marked with a red minus sign) and added In the old placeholder.js files. Can you restore the deleted files and remove the placeholder ones?


image

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Looks good Artyom! One bug I noticed is the text and logo in the header gets clipped on mobile and tablet screens. It's probably due to the changes you made to the header. This isn't an issue on the main branch so maybe refer to the code there.

Screen Shot 2022-06-01 at 4 51 42 PM

Screen Shot 2022-06-01 at 4 52 01 PM

**Review by petabite — APPROVED** [review]
👌

**Review by dnanjunda — APPROVED** [review]
LGTM

**Pull request merged**
