### PR TITLE
Feature/jacobayu/pass fail component

### LINKED ISSUE #43: Waiting on foster component

### LINKED ISSUE #44: Message to foster component

### PR DESCRIPTION
**Pull request by jacobayu**
### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added the PassFail as well as LoadingBox components to be used in future pages

### Testing
How did you confirm your changes worked? 
- Visually confirmed changes as well as printed changes of text box to ensure changes were being properly recorded
- To test yourself uncomment the components in the landing.js page

### Confirmation of Change 
Screen Shot 2022-04-10 at 6 50 28 PM
Pass/Fail Component

Screen Shot 2022-04-10 at 6 50 44 PM
Loading Component

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

### CODE REVIEW

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Looks nice! Here's a few things I noticed:

1. The loading box component resizes when the width changes but not when the height changes:

https://user-images.githubusercontent.com/57281768/163695969-af8cbf3c-dfa4-49f1-93d8-6a568a3fbf3c.mov


2. Can you add a bit more space between the waiting line and the current stage line in the loading component?
3.  The pass fail component also seems to resize only when the width changes. Also, there's a bit of scroll within the text box, which shouldn't happen.

https://user-images.githubusercontent.com/57281768/163696164-3b482393-fdf2-4b58-b649-c0adb8132afa.mov


4. Can you style the confirm button like it is in the designs? There's a similar button on other pages so you can refer to that code if needed.
Screen Shot 2022-04-16 at 6 16 26 PM

5. This component will be a popup so make sure your code is implemented to work that way and add an "X" button in the top left corner that closes the popup.

**Review by willji0023 — CHANGES_REQUESTED** [review]
Good work! Besides the things Dhanush suggested, here some small things I noticed:

1. I think the left and right padding inside the text editor could be increase a tiny bit, since right now the text gets very close to the left and right edges.
image

2. I'm not sure if this is intended, but currently in the case when there is a word that ends up wider than the the device's screen size, the text editor begins extending, and the rest of the screen moves with it. Is it possible to force the width of the text editor to always stay the same?

https://user-images.githubusercontent.com/23545972/164206402-1260dd54-14e0-4d9b-b133-2dcbf05a15ce.mp4



3. Since this is only true for a few phones with smaller screen widths, iIt may or may not be worth scaling the image down when the loading component wrapper becomes smaller than the size of the image, since on very small screen widths the loading component has some overlap. 
image

**Review by willji0023 — APPROVED** [review]
Nice, LGTM!

**Review by dnanjunda — APPROVED** [review]
LGTM!

**Pull request merged**
