### PR TITLE
Feature/willji0023/meeting scheduling component

### LINKED ISSUE #39: Calendar Appointment Scheduling Component

### PR DESCRIPTION
**Pull request by willji0023**
### Administrative Info
[GitHub Issue #39]

### Changes
What changes did you make?
- Added the calendar scheduling component to be used on the Initial Interview, Home Screen, and Meet & Greet Scheduling stages for Fosters.

### Testing
How did you confirm your changes worked? 
- Visually compared component to its desktop and mobile styling on Figma

### Confirmation of Change 
- For testing purposes the component can be seen by going to `/Calendar`

| Calendar Scheduling Component |
| --- |
| image |

| Mobile View|
| --- |
|image|

### CODE REVIEW

**Review by portoaj — COMMENTED** [review]
Hi Will,

Just a few things to look at before I think this PR can get pushed through.

1. I think the green "choose" visual for the time selection button seems like it should be a hover state instead of showing that the user already selected it. Might want to bring this up with Dhanush/ design team to clarify.
image
2. The Figma shows the calendar without any scrollbar which makes it look to me like you are using a bit more spacing or a larger size for each circle which is making it overflow. I think the component would look much better without a scrollbar so I think this should probably be addressed at least for Desktop.
image
3. Is the lock from now until July on purpose? Not sure if this is intentional but I can't scroll past July in the Calendar. Would make sense if that's on purpose so users can't plan out events too far into the future but just checking this is intentional.

**Comment by dnanjunda** [comment]
> Hi Will,
> 
> Just a few things to look at before I think this PR can get pushed through.
> 
> 1. I think the green "choose" visual for the time selection button seems like it should be a hover state instead of showing that the user already selected it. Might want to bring this up with Dhanush/ design team to clarify.
>    image
> 2. The Figma shows the calendar without any scrollbar which makes it look to me like you are using a bit more spacing or a larger size for each circle which is making it overflow. I think the component would look much better without a scrollbar so I think this should probably be addressed at least for Desktop.
>    image
> 3. Is the lock from now until July on purpose? Not sure if this is intentional but I can't scroll past July in the Calendar. Would make sense if that's on purpose so users can't plan out events too far into the future but just checking this is intentional.

In the designs, the green "choose" button is defined as just showing the time selected so we can leave it as that for now unless the client wants to change it. We decided to restrict the selection to 3 months in the future so yes the lock is intentional.

**Comment by willji0023** [comment]
Gonna leave the branch name how it is for now since renaming it would close this PR and comment history

**Review by portoaj — APPROVED** [review]
Looks good👍

**Review by dnanjunda — APPROVED** [review]
LGTM! Nice work Will

**Pull request merged**
