### PR TITLE
Feature/jacobayu/meeting component

### LINKED ISSUE #28: Status update and meeting scheduled components

### PR DESCRIPTION
**Pull request by jacobayu**
### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added component for meeting confirmations

### Testing
How did you confirm your changes worked? 
- Manually viewed and tested the component

### Confirmation of Change 
Upload a screenshot, if 
Screen Shot 2022-01-18 at 3 25 47 PM
without title

Screen Shot 2022-01-18 at 3 26 07 PM
with title

possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

### CODE REVIEW

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Looks nice Jacob! Just a couple things to fix:

1. For both components, can you increase the width of the black border, similar to the designs? It looks like the text card is a bit too wide, so maybe decrease its width.

From figma:
meeting_figma

Your component:
meeting

2. Can you increase the font size of the title and make it bold? Also, add some padding on the left for the text card.
3. For the status update component, right now you have a prop for the ambassador name, which is fine. Once we have accounts set up, we also want to display their profile picture. Can you add a prop for this? You can just use a random photo for now.
4. For some of the mobile screens, your component is too wide and it results in some horizontal scroll:
meeting_mobile

5. Move your css files to the "css" folder and delete the "styles" folder.
6. Make sure to resolve merge conflicts and fix the linting errors.

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Looks much better Jacob! Few minor things:

1. Can you increase the font size of the title? Check the value specified on figma.
2. For some of the mobile screens, the component still overflows and the border is cut off:
component_mobile

3. Can you increase the width of the black border for mobile screens as well? Something like this:
mobile

**Review by petabite — APPROVED** [review]
Looks good! Responsiveness is working perfectly on my end. One small thing I noticed is that the font size on mobile looks small:

image

Other than that, it looks ready to be merged!

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Nice Jacob! Like Philip said above, the only thing I noticed is the font size on mobile (less than 750px) is too small. For the interview info part, you can try reducing the padding on the left and right to have more space for text.

**Review by dnanjunda — APPROVED** [review]
LGTM!

**Pull request merged**
