### PR TITLE
Feature/jacobayu/email sender

### LINKED ISSUE #56: Email Automation for Contact Page
- connect contact page to backend
- use nodemailer

### PR DESCRIPTION
**Pull request by jacobayu**
### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added email automation function

### Testing
How did you confirm your changes worked? 
- I sent various emails to my own different emails as well as my roommates' emails

To test on your own, import the sendEmail function
create a locals object with the following fields, all strings
{
team:
name:
message:
email:
}

call function with sendEmail("message", "YOUR_EMAIL@gmail.com", object you created before)

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

### CODE REVIEW

**Review by parth4apple — CHANGES_REQUESTED** [review]
Hello Jacob, looks good overall just noticed a few small things.

1. For some reason the form validation for the text being empty disappeared. This was probably something we didn't catch when I built the frontend for this page. 
The fix is to replace lines 90 and 91 in contactStyles.css to 
  left: 30vw;
  top: 7vh;
Please include this in your PR.

2. I noticed that enters and formatting are not included in the email that is sent to admin. 
This message:
Screen Shot 2022-05-16 at 1 53 45 PM

Gets sent as this in the email:
Screen Shot 2022-05-16 at 1 54 10 PM

If you could include \n characters in the sent email, I think that would make things more readable for the admin.

3. This isn't really a change, but I was thinking shouldn't the user's message also be emailed themself for their own future reference? I don't know if it is needed or if it would take too long to implement this, but maybe run it by Dhanush.

**Comment by dnanjunda** [comment]
> 3. This isn't really a change, but I was thinking shouldn't the user's message also be emailed themself for their own future reference? I don't know if it is needed or if it would take too long to implement this, but maybe run it by Dhanush.

Nice catch Parth! I think it would be good to cc the user so that they have a reference of the email. @jacobayu Can you do this?

**Review by parth4apple — APPROVED** [review]
LGTM.

**Review by dnanjunda — APPROVED** [review]
LGTM! Nice work Jacob

**Pull request merged**
