### PR TITLE
Feature/parth4apple/stage 5

### LINKED ISSUE #50: Home Screen Information Component (Stage 5)

### PR DESCRIPTION
**Pull request by parth4apple**
### Administrative Info
[GitHub Issue #]

### Changes
What changes did you make?
Completed the home screen information component on stage 5 of the admin view. 

### Testing
Comment out the FosterApplication/FosterAgreement conditional rendering code in the Application.js file (lines 516-520) and uncomment line 521. 
**EDIT: TESTING CAN NOW BE DONE BY GOING TO THE CONTENT IN STAGE 5 OF THE APPLICATION PAGE.

NOTE: This branch should be called stage-5 not stage-6.

### CODE REVIEW

**Review by dnanjunda — CHANGES_REQUESTED** [review]
This is looking nice Parth! Here's some small things I noticed:

1. Your component overlaps with the progress bar at the top, so you need to add padding to bump it down more.
overlap


2. I know you used Jacob's component for the left side of this, but the content doesn't match. Maybe you can pass in props to indicate what Jacob's component is being used for and then display the appropriate content. If needed, you can talk to Jacob and work with him to add this. Here's what the content should be:
stage5

3. The position of the "dog met" and "dog in home" names seems off. I think you can move it to the left more and center it as well.
4. On a regular laptop screen, there's a bit of scroll within your component. Can you size everything down a little to get rid of this?
https://user-images.githubusercontent.com/57281768/166089744-dbd67315-6ee2-4b4f-a80e-fd66b8ab2d39.mov

5. Also merge main into this branch and resolve the merge conflicts. This might fix some of the bugs listed above. Philip also added functionality for placing a component in a particular stage, so we shouldn't have to comment out the application/agreement anymore.

**Review by jacobayu — CHANGES_REQUESTED** [review]
Hello looks pretty good, just one small thing in addition to the comments Dhanush left, but in the figma the names of the dogs look like they are centered and stacked on top of each other, but yours seem to be right aligned.

Screen Shot 2022-05-09 at 11 06 18 PM
Screen Shot 2022-05-09 at 11 48 00 PM

Also regarding the left side of the component, I think it shouldn't be too bad to modify the component so we can pass in props for the fields as long as there are five rows, which thankfully there are, but for different number of rows I think the grid will break LOL

**Review by dnanjunda — CHANGES_REQUESTED** [review]
This is much better! Few really minor things:

1. This component should be in step 5 content instead of step 4.
2. I know on Figma the title is "Home Screen Information" but it doesn't really fit the information here. Can you change it to "Meet & Greet Information"?
3. Add some padding below your component just so that there's some white space there.
4. Couple things here. Within your component, the right margin seems bigger than the left. Can you make them the same so it looks centered? Also, style the border for the "dog in home" like it is in the designs. You just need to decrease the border width and make the corners more rounded. Last thing, the "confirm" button has a small gray border. Can you get rid of that?
stage5

**Review by jacobayu — APPROVED** [review]

**Review by dnanjunda — APPROVED** [review]
LGTM!

**Pull request merged**
