### PR TITLE
Feature/parth4apple/manage dog profiles

### LINKED ISSUE #52: Manage Dog Profiles Page
Also includes the create a new dog profile popup form

### PR DESCRIPTION
**Pull request by parth4apple**
### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
Almost finished the manage dog profiles page. 
TODO:
- Add image hosting and make corresponding changes to frontend

### Testing
How did you confirm your changes worked? 
Run the frontend and backend. Go to manage dog profiles page and experiment with the functions.
- Click on a create a new dog
- Click on view all/ view less
- Click on any of the dogs listed (and then click on edit)

### Confirmation of Change 

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

### CODE REVIEW

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Looking good! There's a lot of components in this PR so quite a few things to fix:

1. Can you make the "create a new dog profile" button look like the design? The plus just looks too big.
2. The "Dog Profile" component that opens when a card is clicked needs to be a popup over the existing page. So, make sure to blur the background and if it doesn't fit in the default body area then have it size down or add a scroll within the popup (whichever is easier). It just shouldn't extend beyond the screen like this:
Screen Shot 2022-05-19 at 6 05 27 PM

3. Make the cursor a pointer when hovering over any of the dog cards and buttons (close popup button).
4. For the text in the popup (age, gender, breed, weight), you don't need to right align it.
5. Both the create dog and update dog popups overflow right now. You need to restrict the height of these components and also blur the background.
Screen Shot 2022-05-19 at 6 08 25 PM
Screen Shot 2022-05-19 at 6 08 55 PM

6. There's no need for the "Category" field when creating a new dog profile because it will be new by default.
7. When an input field is selected, it has a blue border around it. Can you get rid of that? It should be a 1 line fix.

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Almost there Parth! Few things to look at:

1. For some reason, when the dog profile popup is open, there's some extra scroll on the page. Can you get rid of this?

https://user-images.githubusercontent.com/57281768/169640816-2bf75e3e-f144-4897-8c67-efde03326e95.mov


2. Similar to how you changed the border color for input fields, can you do that for the "Images" field? It still has the old outline that we were discussing.
3. For the dog profile popup, can you blur the background like this? Take a look at Will's Profile page popup (Popup.js). It has the exact same background blur. 

Screen Shot 2022-05-21 at 12 23 16 AM

4. For the other two form popups, have it extend further over the screen (just height wise) and make the background like this:

Screen Shot 2022-05-21 at 12 23 04 AM

5. For the create a dog popup, change the button text to "Submit" instead of "Continue."

**Review by willji0023 — CHANGES_REQUESTED** [review]
Nice work! Here's just some minor things I noticed:
1. I noticed the Internal Foster Notes, Vetting Information, and Background Information sections don't have any scroll when one of their section overflows.
image 
image
I think adding a scroll to each section might help.

2. I think currently its pretty easy for the left-side text to overlap with the right-side text on mobile. Maybe at a certain width you could bring the black text underneath the green text instead of keeping them side by side?
image

3. The space between the add more images button and the text could increase a tad on mobile. 
image

Lemme know if these suggestions are too minor / tricky to fix and might not be fixable by our current deadline.

**Review by willji0023 — APPROVED** [review]
LGTM

**Review by dnanjunda — APPROVED** [review]
LGTM! Great work Parth

**Pull request merged**
