### PR TITLE
feature/portoaj/foster-matching-page

### LINKED ISSUE #49: Foster Matching Component (Part 4 of Signup Process)

### PR DESCRIPTION
**Pull request by portoaj**
### Changes
What changes did you make?
Created the foster matching page, including a SplitCardContainer component to hold both of the main containers used in the page.

### Testing
How did you confirm your changes worked? 
Tested across different resolutions to make sure that things scaled properly.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
Screen Shot 2022-04-27 at 12 39 27 PM

### CODE REVIEW

**Review by dnanjunda — CHANGES_REQUESTED** [review]
This is coming along well Andrew! There's some changes that are necessary though:

1. Can you style the confirm button to look more like the design? Parth has the exact same button in his stage 5 PR so take a look at that if needed.
2. Right now, when I select a dog, the checkbox is just selected. Can you make the white background turn into light green and the checkbox be green as well? It should look like this:
select_dogs

3. Also add a bit more padding to the left and right of the dog image within the card, as shown in the image above.
4. Within the internal foster notes area, there's some overlap with the content. Maybe you can reduce the font size for the notes and move the edit button to the right a bit.
internal_notes

5. The "status updated" label looks weird. I think it would be better to center it within the green box. Also, add a little bit of padding above the titles "foster profile" and "available dogs."
6. Since Philip has added functionality for putting a component in a particular stage, can you put this component in the appropriate stage and get rid of the route you added?
7. Merge main into your branch and fix the merge conflicts.

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Looks much better! Just a couple more things:

1. Add some padding below the "confirm" button so that it's not all the way at the bottom. Also, decrease the padding at the top a bit between the progress bar and your component. It's just a lot of white space wasted.
2. The dog cards look much better now. Can you make it so that they can be selected by clicking anywhere on the card? Let me know if this is too hard though.
3. Can you add a bit of padding above the titles "Foster Profile," "Available Dogs," "Shelby," and "Internal Foster Notes"?
4. This is a nitpick but the dog image doesn't look horizontally centered within the card. There's more padding on the left than the right.
5. For the notes section, I think it would be easier to just have the edit button on a separate line below the notes text. Right now if the string is longer, it still overlaps:
foster_notes

**Review by parth4apple — CHANGES_REQUESTED** [review]
Hey Andrew, here are some things I noticed.

1. Add "cursor: pointer" to all the select dog cards, the confirm button, the edit buttons, and view application button to let the user know that those elements are clickable.

2. Put the edit button on the internal foster notes at the bottom of the box rather than the top and decrease the width of the text so that the button fits. 
Current:
Screen Shot 2022-05-23 at 2 05 04 PM
Figma:
Screen Shot 2022-05-23 at 2 05 23 PM
Honestly I think your implementation looks better than the figma's. Maybe run it by Dhanush to see if this change is ignorable. 


3. I think your changes in defaultbody.css might be problematic for some of the other pages. I'd say revert them and try to modify your code to create your desired behavior. 
Screen Shot 2022-05-23 at 2 35 52 PM


4. When you use styled components, you don't have to export styled objects if you are only using them in the current file; exporting unnecessarily is inefficient. So instead of `export const Container...` use `const Container...`.
Refer to docs for more info: https://styled-components.com/docs/api

5.  Center the component horizontally within the application page. If you need help with this, I'd ask Phillip.
Screen Shot 2022-05-23 at 2 22 10 PM

6. I'm not sure if mobile views are something we for this page. If they are then the content overflows on mobile view off the screen (set a max-width to a % of vw), if we don't care then ignore this. Also I think reverting your defaultbody.css changes might fix this automatically.

7. Use `git merge main` on your root directory and resolve your merge conflicts. Look at the pacakge.json on the main branch from a browser view, and make sure you have everything that's present in there. Then delete package-lock.json and `npm install`. If you do this on the root and client side this should resolve the merge conflicts. Also manually resolve the merge conflicts in Application.js

**Comment by dnanjunda** [comment]
> 

I think we can just leave the edit button as it is. Like you said, it looks good and isn't worth moving right now. And for the point about mobile views, this component is only used on the admin side, so we can skip mobile designs for now. So, @portoaj you can just skip those two comments.

**Review by parth4apple — APPROVED** [review]

**Review by dnanjunda — APPROVED** [review]
LGTM!

**Pull request merged**
