### PR TITLE
Profiles Page

### LINKED ISSUE #15: Profile page

### PR DESCRIPTION
**Pull request by willji0023**
### Administrative Info
[GitHub Issue #15]

### Changes
What changes did you make?
- Created components for profile sections, cards, popup, and buttons
- Styled Profile page for both desktop and mobile

### Testing
How did you confirm your changes worked? 
- Viewed and tested components manually at different screen widths
- Compared style to Figma

### Confirmation of Change 
| Profile page |
| --- |
| image |

| Viewing My Profile |
| --- |
| image |

| Editing My Profile |
| --- |
| image|

### CODE REVIEW

**Review by dnanjunda — CHANGES_REQUESTED** [review]
This looks great William! Most of the things I noticed are minor stuff:

1. This might just be my screen size, but can you decrease the height of the popup so that there's no scroll (on regular desktop screens)? I think you can decrease the spacing a bit between all the contents.
2. When there is scroll, make the scrollbar be visible at all times. Otherwise it's not obvious that there's more content on the popup.
3. The close button on the popup is pretty small so make it a bit bigger.
4. Add a bit of padding between the "edit profile" button and the "save changes" button and the bottom of the popup.
5. On some mobile screens the popup looks a bit small, so can you make it take up the width of the screen (with a small amount of padding) like this:
Profile_popup

6. Similar to the point above, the profile cards look a bit small on some of the screens. So for widths less than like 400px, make it a single column. 
profile_mobile

7. Merge main with your branch and include the navbar for this page

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Looks nice William! You're very close to finishing this:

1. The "save changes" button looks good on mobile screens but for desktop, add padding between the button and the bottom of the popup. This only seems to happen when the popup can't fit all the content and there's scroll:
profile_popup

2. Not sure if you missed it in the previous comment, but please make the scrollbar visible at all times when there's scroll. There should be a quick 1 line css fix to this.
3. On mobile screens, there's a big gap above the "my profile" button at the top. Can you reduce this space?
4. This isn't important at all, but I'm mentioning it since I noticed it. Only on Galaxy Fold, there's horizontal scroll because the content doesn't fit. If you have a quick fix for this, then go for it but otherwise just leave it for now.
mobile_popup

**Review by artyom2001 — COMMENTED** [review]
I saw all of Dhanush's comments and I think you addressed all of them. Here are some other things I noticed that I wanted to note here:

1. When I click on the "Save Changes" button, my changes are not saved and the phone number and email go back to the original ones. I assume this will be fixed once we connect the page to the database.
2. Specifically on Firefox, the blurred effect when clicking on the profile doesn't work for me but works on other browsers (Chrome, Edge, etc.).
image
3. For some larger screen sizes, the navbar begins to overlap with the actual page. Adding to this, the navbar doesn't extend down when scrolling down on the profile page. I'm fairly sure that this is an issue with the navbar code instead, but I still wanted to mention it here so you are aware of it. 
image

**Comment by willji0023** [comment]
Not sure if there's a clean way to add a blur filter to backdrops on browsers that don't support backdrop-filter (seems like only Firefox and Internet Explorer don't), so instead I made a support query to check if the browser supports backdrop-filter or not, and if it doesn't, the popup background is grayed out instead.

**Review by artyom2001 — APPROVED** [review]
Everything looks good to me. The graying out works for me on Firefox, so I think this PR is ready to be merged into the main branch. The remaining changes to the profile page can be addressed once we connect it to the database, so it can be another PR.

**Review by dnanjunda — APPROVED** [review]
LGTM! Nicely done Will

**Pull request merged**
